In [1]:
!pip install numpy #command for installing numpy in jupyter notebook

ERROR: Invalid requirement: '#command'


In [2]:
!pip install --upgrade pip

  Using cached pip-24.2-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-24.2-py3-none-any.whl (1.8 MB)


ERROR: To modify pip, please run the following command:
D:\anaconda\envs\venv\python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

#create array using numpy
#create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape) # shape tells the dimension of given array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2= np.array([1,2,3,4,5])
arr2.reshape(1,5) #reshape is used for changing the dimension of the given array

array([[1, 2, 3, 4, 5]])

In [7]:
arr3= np.array([[1,2,3,4,5],[2,3,4,5,6]]) #creating a 2D array
print(arr3)
print(arr3.shape) #tell the dimension of given array

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [8]:
# numpy.arange(x,y) :- arange function is used to create an array within the range from x,y and y is not included
np.arange(0,10).reshape(5,2) 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
# numpy.ones(x,y) :- it creates an array with x rows and y columns and all elements are going to be one
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
#identity matrix
np.eye(3) #this will create an identity matrix with 3D array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [12]:
### Numpy vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise addition
print("Addition:",arr1+arr2)

#Element wise subtraction
print("Subtraction:",arr1-arr2)

# Element wise multiplication
print("Multiplication:",arr1*arr2)

# Element wise division
print("Division:",arr1/arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [13]:
## Universal Function 

arr = np.array([2,3,4,5,6])
#Square root 
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

#Sine
print(np.sin(arr))

#Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [14]:
# array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [16]:
#accessing any specific element in array
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [17]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [18]:
#Modifing element in an array
arr[0][0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [19]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [20]:
## Statistical concept -- Normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data =(data - mean)/ std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [21]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean = np.mean(data)
print("Mean:",mean)

#Median
median = np.median(data)
print("Median:",median)

#Standard deviation 
std_deviation = np.std(data)
print("Standard Deviation:", std_deviation)

#Variance
variance = np.var(data)
print("Variance:",variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [22]:
# Logical operation 
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data>5) #print true where element value is greater than 5
print(data[data >5]) # returns the index of element where the element value is greater than 5

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
