# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [4]:
import numpy as np

# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1,21, size=(5,5))
print("Originally Array: ")
print(array)

# Replace all the elements in the third column with 1
array[: , 2] = 1
print("Modified Array")
print(array)



Originally Array: 
[[15 11  6 13 10]
 [ 3  5  9 18  5]
 [19  3  7  6  6]
 [ 1 18 13  9  6]
 [ 1 19  8 11 20]]

[[15 11  1 13 10]
 [ 3  5  1 18  5]
 [19  3  1  6  6]
 [ 1 18  1  9  6]
 [ 1 19  1 11 20]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [5]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16. 
array = np.arange(1,17).reshape(4,4)
print("Originally Array:")
print(array)

# Replace the diagonal element with 0
np.fill_diagonal(array,0)
print("\nModified Array:")
print(array)

Originally Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Modified Array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [8]:
# Create a Numpy array of shape(6,6) with values from 1 to 36
array = np.arange(1,37).reshape(6,6)
print("Original array:")
print(array)
 
# Extract the sun-array consisting of the 3rd to 5th rows and 2nd to 4th columns
print()
print(array[2:5,1:4])

Original array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [9]:
# Create a numpy array of shape(5,5) with random integers
array = np.random.randint(1,25 , size=(5,5))
print("Original array:")
print(array)
print()

# Extract the element on the border
border_elements = np.concatenate((array[0,:], array[-1,:], array[1:-1 ,0], array[1:-1,-1]))
print("Border Elements: ")
print(border_elements)

Original array:
[[ 6 14  3 19  7]
 [22  3 19 23 24]
 [ 7  5  4  7  5]
 [12 21 19 22 15]
 [11 16 16  9 11]]

Border Elements: 
[ 6 14  3 19  7 11 16 16  9 11 22  7 12 24  5 15]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [11]:
# Create two numpy Arrays of shape (3,4) filled with random integers.
array1 = np.random.randint(1,13,size=(3,4))
array2 = np.random.randint(1,13,size=(3,4))
print("Array1 :")
print(array1,end="\n")
print("Array2 :")
print(array2)

# perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1/array2

print("Element wise addition :")
print(addition)
print("Element wise subtraction:")
print(subtraction)
print("Element wise multiplication: ")
print(multiplication)
print("Element wise division:")
print(division)

Array1 :
[[ 8  6  2  7]
 [ 3  9  4  1]
 [ 8  8 11  3]]
Array2 :
[[ 3  7  8  6]
 [ 1  6  1  1]
 [10  6  6  1]]
Element wise addition :
[[11 13 10 13]
 [ 4 15  5  2]
 [18 14 17  4]]
Element wise subtraction:
[[ 5 -1 -6  1]
 [ 2  3  3  0]
 [-2  2  5  2]]
Element wise multiplication: 
[[24 42 16 42]
 [ 3 54  4  1]
 [80 48 66  3]]
Element wise division:
[[2.66666667 0.85714286 0.25       1.16666667]
 [3.         1.5        4.         1.        ]
 [0.8        1.33333333 1.83333333 3.        ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [12]:
# Create a Numpy array of shape (4,4) with valued from 1 to 16.
array = np.arange(1,17).reshape(4,4)
print("Original Array: ")
print(array)

# Compute the row-wise and column-wise sum
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row wise sum :")
print(row_sum)
print()
print("Column wise sum :")
print(column_sum)

Original Array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise sum :
[10 26 42 58]

Column wise sum :
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [13]:
#create a numpy array of shape(5,5) filled with random integers.

array = np.random.randint(1,26, size=(5,5))

# Compute the mean, median, Standard deviation, and variance of array
mean = np.mean(array)
print("Mean :", mean)

median = np.median(array)
print("Median :",median)

std_dev = np.std(array)
print("Standard Deviation :",std_dev)

variance = np.var(array)
print("Variance :",variance)

Mean : 11.68
Median : 12.0
Standard Deviation : 8.965355542308403
Variance : 80.3776


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [14]:
# Create a numpy of array of shape (3,3) with values from 1 to 9
array = np.arange(1,10).reshape(3,3)
print("Original array :")
print(array)

#Normalize the array
mean = np.mean(array)
std_dev = np.std(array)

normalized_array = (array - mean)/std_dev

print("Normalized array:")
print(normalized_array)

Original array :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [15]:
#creat a numpy array of shape(3,3) filled with random integers

array = np.random.randint(1,11,size = (3,3))
row_array = np.random.randint(1,11,size=(3,))
print("Original Array: ")
print(array)
print("1D array:")
print(row_array)

#Add a 1D array of shape(3,) to each row of the 2D array using broadcasting
result = array + row_array
print("Resulting array :")
print(result)

Original Array: 
[[5 9 8]
 [8 2 3]
 [2 3 9]]
1D array:
[3 6 2]
Resulting array :
[[ 8 15 10]
 [11  8  5]
 [ 5  9 11]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [17]:
# Create a numpy array of shape (4,4) filled with random integers.
array = np.random.randint(1,17 , size=(4,4))
row_array = np.random.randint(1,17,size=(4,))
print("Original array:")
print(array)
print()
print("1D array :")
print(row_array)

# Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting 
result = array - row_array
print("Resulting Array :")
print(result)

Original array:
[[ 6  5  3  8]
 [14  6 16  2]
 [ 7  5 10 16]
 [ 5 14 13  4]]

1D array :
[ 9  5  8 11]
Resulting Array :
[[-3  0 -5 -3]
 [ 5  1  8 -9]
 [-2  0  2  5]
 [-4  9  5 -7]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [21]:
# Create a NumPy array of shape (3, 3) representing a matrix
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Original matrix:
[[ 5 10  2]
 [ 5  8  4]
 [ 5  5  5]]
Determinant: 19.99999999999999
Inverse:
[[ 1.   -2.    1.2 ]
 [-0.25  0.75 -0.5 ]
 [-0.75  1.25 -0.5 ]]
Eigenvalues: [16.56356197+0.j          0.71821901+0.83164367j  0.71821901-0.83164367j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [22]:
# Create two NumPy arrays of shape (2,3) and (3,2). 
array1 = np.random.randint(1,11,size=(2,3))
array2 = np.random.randint(1,11,size=(3,2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform matrix multiplication on these arrays
result = np.dot(array1,array2)
print("Resulting array: ")
print(result) 

Array 1:
[[ 1 10  5]
 [ 6  3  9]]
Array 2:
[[7 4]
 [2 6]
 [6 8]]
Resulting array: 
[[ 57 104]
 [102 114]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


In [24]:
#create a NumPy array of shape (3,3) with values from 1 to 9.
array = np.arange(1,10).reshape(3,3)
print("Original Array")
print(array)

# Reshape the array to shape (1,9) and the to shape (9,1)
array = array.reshape(1,9)
print("Reshaped Array of size (1,9)")
print(array)
array = array.reshape(9,1)
print("Reshaped Array of size (9,1)")
print(array)

Original Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped Array of size (1,9)
[[1 2 3 4 5 6 7 8 9]]
Reshaped Array of size (9,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [25]:
# Create a Numpy array of shape(5,5)
array = np.random.randint(1,26, size=(5,5))
print("Original array:")
print(array)
print()

# Flatten the array and then reshape it back to (5,5)
flatten_array = array.flatten()
print("Flatten array :")
print(flatten_array)
print()

reshaped_array = flatten_array.reshape(5,5)
print("Reshaped Array :")
print(reshaped_array)

Original array:
[[ 5  9  8 10  4]
 [18 22 12 22 16]
 [13 16 15  2 22]
 [10  8 13 20 10]
 [21 17  2 13 16]]

Flatten array :
[ 5  9  8 10  4 18 22 12 22 16 13 16 15  2 22 10  8 13 20 10 21 17  2 13
 16]

Reshaped Array :
[[ 5  9  8 10  4]
 [18 22 12 22 16]
 [13 16 15  2 22]
 [10  8 13 20 10]
 [21 17  2 13 16]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [26]:
# Create a NumPy array of shape(5,5) filled with random integer 
array = np.random.randint(1,26, size=(5,5))
print("Original Array :")
print(array)

# Use fancy indexing to extract the elements at the corners of the array 
corners = array[[0,0,-1,-1],[0,-1,0,-1]]
print("Corner Elements: ")
print(corners)


Original Array :
[[25 22  2  1 14]
 [ 4  3 11 12  7]
 [19 13  5  9  8]
 [24 10 24  7 10]
 [ 5 14  1 22 25]]
Corner Elements: 
[25 14  5 25]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [28]:
# Create a NumPy array of shape (4,4) filled with random integers
array = np.random.randint(1,17,size=(4,4))
print("Original Array: ")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified Array: ")
print(array)


Original Array: 
[[ 9 10 12  7]
 [14 14  4 11]
 [ 2 13  2  7]
 [ 7  1  2  1]]
Modified Array: 
[[ 9 10 10  7]
 [10 10  4 10]
 [ 2 10  2  7]
 [ 7  1  2  1]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.


In [31]:
# Create a structured array with fields 'name' (string), 'age'(integer), and 'weight'(float)
data_type = [('name','U10'),('age','i4'),('weight','f4')]
data = np.array([('Alice',35,55.5),('Bob',30,85.5),('Charlie',32,50)],dtype=data_type)
print("Original Array:")
print(array)

#Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age: ")
print(sorted_data)

Original Array:
[[ 9 10 10  7]
 [10 10  4 10]
 [ 2 10  2  7]
 [ 7  1  2  1]]
Sorted array by age: 
[('Bob', 30, 85.5) ('Charlie', 32, 50. ) ('Alice', 35, 55.5)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [32]:
# Create a structured array with fields 'x' and 'y' (both integers)
data_type =[('x','i4'),('y','i4')]
data = np.array([(1,2),(3,4),(5,6)], dtype=data_type)
print("Original Array:")
print(data)

# Compute the Euclidean distance between each pair of points.
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original Array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.


In [35]:
import numpy.ma as ma

# Create a masked array of shape (4,4) with random integers and mask the elements greater than 10
array = np.random.randint(1,17,size=(4,4))
masked_array = ma.masked_greater(array,10)
print("Original array:")
print(array)
print()
print("Masked Array ")
print(masked_array)

# Compute the sum of unmasked elements
ele_sum = masked_array.sum()
print("Unmasked element sum")
print(ele_sum)

Original array:
[[ 5 10  1 15]
 [ 4 11 14  4]
 [ 6 13  9 10]
 [16  5  3  7]]

Masked Array 
[[5 10 1 --]
 [4 -- -- 4]
 [6 -- 9 10]
 [-- 5 3 7]]
Unmasked element sum
64


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [36]:
# Create a masked array of shape (3,3) with random integers and mask the diagonal elements.
array = np.random.randint(1,10,size=(3,3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original Array:")
print(array)
print("Masked Array: ")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
unmasked_mean = masked_array.mean()
masked_array = masked_array.filled(unmasked_mean)
print("Modified Masked array :")
print(masked_array)


Original Array:
[[6 1 5]
 [5 4 7]
 [4 7 1]]
Masked Array: 
[[-- 1 5]
 [5 -- 7]
 [4 7 --]]
Modified Masked array :
[[4 1 5]
 [5 4 7]
 [4 7 4]]
